import "./globals.css";
import type { Metadata } from "next";
import { Fira_Sans_Condensed } from "next/font/google";

import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { NextUIProvider } from "@nextui-org/react";

const font = Fira_Sans_Condensed({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider >
      <html lang="en">
        <body className={`${font.className} antialiased`}>
          <ConvexClientProvider>
            <NextUIProvider>
              {children}
            </NextUIProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>

  );
}
